---
Questions:
  - question: "Question1"
    keys: [ "q1", "q01", "_1" ]
    grade: 25
    partial_questions:

  - question: "Question2"
    keys: [ "q2", "q02", "_2" ]
    grade: 25
    partial_questions:

  - question: "Question3"
    keys: ["q3", "q03", "_3"]
    grade: 25
    partial_questions:

  - question: "Question4"
    keys: [ "q4", "q04", "_4" ]
    grade: 25
    partial_questions: